import localFont from "next/font/local";
import { Playfair_Display, Noto_Sans_Thai } from 'next/font/google'
import "./globals.css";
import NavBar from "./components/navbar/NavBar";


const playfair_display = Playfair_Display({
  subsets: ['latin','latin-ext'],
  weight: ['400','700'],
})

const noto_sans_thai = Noto_Sans_Thai({
  subsets: ['latin','latin-ext','thai'],
  weight: ['300', '400', '500', '600'],
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "EZLAW",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${noto_sans_thai.className} antialiased`}
      >
        <header>
          <NavBar />
        </header>
        <main>
            {children}
          </main>
      </body>
    </html>
  );
}
